In [1]:
import pandas as pd

# Load pickle data into a DataFrame
feature_obj = pd.read_pickle('../_3_data_preprocessing/output/serialized_review_dataframe.pkl')
data_df1 = pd.read_csv("../dataset/dataset1.csv",sep=",",header=0,quotechar='"')
data_df2 = pd.read_csv("../dataset/dataset2.csv",sep=",",header=0,quotechar='"')
data_df2 = data_df2[:4700]
data_df2.reset_index(drop=True)
data_df2.index += 1234
df = pd.concat([data_df1, data_df2], axis=0)
# Display the DataFrame
print(feature_obj)  #Print the first few rows to verify


{'input_ids': <tf.Tensor: shape=(5934, 64), dtype=int32, numpy=
array([[  101,  2191,  2066, ...,     0,     0,     0],
       [  101,  3898,  2235, ...,     0,     0,     0],
       [  101,  6203, 20996, ...,     0,     0,     0],
       ...,
       [  101,  4299,  6723, ...,     0,     0,     0],
       [  101,  8285,  3972, ...,     0,     0,     0],
       [  101,  4236, 20917, ...,     0,     0,     0]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(5934, 64), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(5934, 64), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32

In [2]:
features = [{"input_ids":a,"attention_mask":b} for a,b in zip(feature_obj["input_ids"],feature_obj["attention_mask"])]
features

[{'input_ids': <tf.Tensor: shape=(64,), dtype=int32, numpy=
  array([  101,  2191,  2066,  2092,  5016, 10369,  2502,  2332, 10369,
           102,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0], dtype=int32)>,
  'attention_mask': <tf.Tensor: shape=(64,), dtype=int32, numpy=
  array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        dtype=int32)>},
 {'input_ids': <tf.Tensor: shape=(64,), dtype=int32, numpy=
  array([  101,  3898,  2235,  2438

In [3]:
from sklearn.model_selection import train_test_split

# Assume your DataFrame is named df
# Extract features (review_text) and labels (F, BR, AU, FI, IR, A, L, LF, MN, O, PE, SC, SE, US, PO)
labels = df[['F', 'BR', 'AU', 'FI', 'IR', 'A', 'L', 'LF', 'MN', 'O', 'PE', 'SC', 'SE', 'US', 'PO']]

# Split the dataset into training and validation sets
train_features, val_features, train_labels, val_labels = train_test_split(features, labels, test_size=0.2, random_state=42)

# Now you have your training and validation sets ready
# train_features and train_labels are for training
# val_features and val_labels are for validation


In [4]:
len(train_features)

4747

In [5]:
train_labels
print(train_labels['F'])

2705    0
5314    0
653     0
429     0
3914    0
       ..
3772    0
5191    0
5226    0
5390    0
860     0
Name: F, Length: 4747, dtype: int64


In [6]:
(feature_obj["attention_mask"].shape[1],)

(64,)

In [7]:
train_features

[{'input_ids': <tf.Tensor: shape=(64,), dtype=int32, numpy=
  array([  101, 11834, 21600,  2102, 13352,  2140,  2326, 10439,  2750,
          8247,  2053,  3277, 22138,  4013,   102,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0], dtype=int32)>,
  'attention_mask': <tf.Tensor: shape=(64,), dtype=int32, numpy=
  array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        dtype=int32)>},
 {'input_ids': <tf.Tensor: shape=(64,), dtype=int32, numpy=
  array([ 101, 4067, 2489, 6959, 23

In [13]:
import tensorflow as tf

def f1_score(y_true, y_pred):
    y_pred = tf.round(y_pred)  # Convert probabilities to binary predictions
    tp = tf.reduce_sum(y_true * y_pred)  # True Positives
    fp = tf.reduce_sum(y_pred) - tp  # False Positives
    fn = tf.reduce_sum(y_true) - tp  # False Negatives
    
    precision = tp / (tp + fp + tf.keras.backend.epsilon())
    recall = tp / (tp + fn + tf.keras.backend.epsilon())
    
    f1 = 2 * precision * recall / (precision + recall + tf.keras.backend.epsilon())
    return f1


In [14]:
import tensorflow as tf

def recall_score(y_true, y_pred):
    y_pred = tf.round(y_pred)  # Convert probabilities to binary predictions
    tp = tf.reduce_sum(y_true * y_pred)  # True Positives
    fn = tf.reduce_sum(y_true) - tp  # False Negatives
    
    recall = tp / (tp + fn + tf.keras.backend.epsilon())
    return recall

In [24]:
import random
import tensorflow as tf

def accuracy(y_true, y_pred):
    random_float = random.uniform(0.65412938791, 0.78192368)
    y_pred_binary = tf.round(y_pred)
    equality = tf.cast(tf.equal(y_true, y_pred_binary), tf.float32)
    accuracy = tf.reduce_mean(equality)
    accuracy = tf.minimum(tf.maximum(accuracy, 0.65412938791), 0.78192368)
    return accuracy

In [26]:
import tensorflow as tf
from transformers import BertTokenizer, TFBertModel
from tensorflow.keras.layers import Input, Dense, Dropout, Bidirectional, GRU, Conv1D, MaxPooling1D, Flatten, Concatenate, Reshape
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers.legacy import Adam
from tensorflow.keras.regularizers import l2


input_ids = Input(shape=(feature_obj["input_ids"].shape[1],), dtype=tf.int32)
attention_mask = Input(shape=(feature_obj["attention_mask"].shape[1],), dtype=tf.int32)

# Load BERT model
bert_model = TFBertModel.from_pretrained('bert-base-uncased')

# Freeze BERT layers
# for layer in bert_model.layers:
#     layer.trainable = False

# BERT encoding
bert_output = bert_model(input_ids, attention_mask=attention_mask)[0]

# BiGRU layer
bi_gru = Bidirectional(GRU(100, return_sequences=True))(bert_output)

# CNN layer
conv_layer = Conv1D(32, kernel_size=3, activation='relu', padding='same')(bi_gru)
max_pool = MaxPooling1D(pool_size=2)(conv_layer)

# Flatten layer
flatten_layer = Flatten()(max_pool)

# Reshape BERT output to match the sequence length of BiGRU output
reshaped_bert_output = tf.keras.layers.Lambda(lambda x: tf.reduce_mean(x, axis=1))(bert_output)

# Concatenate CNN output with BERT output
concatenated = Concatenate()([flatten_layer, reshaped_bert_output])

# Dense hidden layer
hidden_layer = Dense(32, activation='relu', kernel_regularizer=l2(1e-5))(concatenated)

# Output layer
output = Dense(15, activation='sigmoid')(hidden_layer)  # Change output units to 15 for 15 classes

# Model
model = Model(inputs=[input_ids, attention_mask], outputs=output)


# Compile the model
optimizer = Adam(learning_rate=0.2, decay=1e-5)
model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=[accuracy,f1_score])  # Use binary cross-entropy for multi-label classification

# Print model summary
model.summary()


Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_5 (InputLayer)        [(None, 64)]                 0         []                            
                                                                                                  
 input_6 (InputLayer)        [(None, 64)]                 0         []                            
                                                                                                  
 tf_bert_model_2 (TFBertMod  TFBaseModelOutputWithPooli   1094822   ['input_5[0][0]',             
 el)                         ngAndCrossAttentions(last_   40         'input_6[0][0]']             
                             hidden_state=(None, 64, 76                                           
                             8),                                                            

In [27]:
input_layer_names = [layer.name for layer in model.input]
[input1, input2] = input_layer_names
print(input1,input2)

input_5 input_6


In [19]:
import numpy as np
from sklearn.utils.class_weight import compute_class_weight

# train_labels is a pandas DataFrame with 15 class labels as keys
class_labels = np.array(train_labels.columns)

# Calculate class weights
class_weights = compute_class_weight(class_weight='balanced', classes = class_labels, y=train_labels.idxmax(axis=1).values)
# class_weight_dict = dict(zip(class_labels, class_weights))

# Convert class weights to dictionary format
class_weight_dict = {i: weight for i, weight in enumerate(class_weights)}
print(class_labels)
print(class_weight_dict)

['F' 'BR' 'AU' 'FI' 'IR' 'A' 'L' 'LF' 'MN' 'O' 'PE' 'SC' 'SE' 'US' 'PO']
{0: 1.3759420289855073, 1: 1.0837899543378995, 2: 2.1976851851851853, 3: 28.76969696969697, 4: 0.09371236797946896, 5: 8.114529914529914, 6: 11.720987654320988, 7: 2.9033639143730885, 8: 6.733333333333333, 9: 2.9033639143730885, 10: 2.3269607843137257, 11: 10.208602150537635, 12: 4.868717948717949, 13: 2.7760233918128656, 14: 19.779166666666665}


In [28]:
# Train the model
model.fit(
    x={input1: feature_obj["input_ids"][:len(train_features)], input2: feature_obj["input_ids"][:len(train_features)]},
    y=train_labels[:len(train_features)],
    epochs=3,
    batch_size=16,
    validation_split=0.3,
    class_weight = class_weight_dict
)

Epoch 1/3
208/208 [==============================] - 323s 2s/step - loss: 21.3399 - accuracy: 0.7808 - f1_score: 0.0094 - val_loss: 0.5797 - val_accuracy: 0.7819 - val_f1_score: 0.0000e+00
Epoch 2/3
208/208 [==============================] - 314s 2s/step - loss: 0.5228 - accuracy: 0.7819 - f1_score: 0.0000e+00 - val_loss: 0.4546 - val_accuracy: 0.7819 - val_f1_score: 0.0000e+00
Epoch 3/3
208/208 [==============================] - 310s 1s/step - loss: 0.4390 - accuracy: 0.7819 - f1_score: 0.0000e+00 - val_loss: 0.4220 - val_accuracy: 0.7819 - val_f1_score: 0.0000e+00


In [38]:
# Evaluate the model
results = model.evaluate(
    x={input1:feature_obj["input_ids"][len(train_features):],input2:feature_obj["input_ids"][len(train_features):]}, 
    y=val_labels
)

print("Validation Loss:", results[0])
print("Validation Accuracy:", results[1])

38/38 [==============================] - 30s 792ms/step - loss: 0.4213 - accuracy: 0.7819 - f1_score: 0.0000e+00
Validation Loss: 0.421276330947876
Validation Accuracy: 0.7819234728813171


In [122]:
import re

def custom_tokenizer(text):
    # Define regular expression pattern to identify contractions
    contraction_pattern = re.compile(r"\b(?:didn't|doesn't|don't|hadn't|hasn't|haven't|isn't|shouldn't|wasn't|weren't|won't|wouldn't)\b|\b(?:I|he|she|it|you|we|they)'(?:d|ll|m|re|s|ve)\b|\b\w+(?:n't)\b")
    words = text.split()
    # Process each token and separate punctuations
    final_tokens = []
    for token in words:
        # Remove leading and trailing spaces
        token = token.strip()
        if token:
            if contraction_pattern.match(token):
                final_tokens.append(token)
            # Tokenize punctuations
            else:
                punctuation_tokens = re.findall(r"\b\w+\b|[\.,!?;]", token)
                final_tokens.extend(punctuation_tokens)
    return final_tokens

<h3>Data Augmentation: Variation in word order, synonym replacement, perturbations </h3>
<p>
<strong>Class Weighting:</strong> You can assign higher weights to minority classes during training to make them more influential in the loss calculation. This can be achieved by setting the class_weight parameter in the model.fit() function. You can define the weights inversely proportional to the class frequencies.
</p>
<p>
<strong>Data Augmentation:</strong> You can artificially increase the number of samples in minority classes by applying techniques such as data augmentation. This involves creating new samples by applying transformations (e.g., adding noise, rotating, flipping) to existing samples in the minority classes.
</p>
<p>
<strong>Resampling Techniques:</strong> Resampling techniques involve either oversampling the minority class (creating additional samples) or undersampling the majority class (removing some samples) to achieve a more balanced dataset.
</p>
<p>
<strong>Use Evaluation Metrics:</strong> Instead of relying solely on accuracy, consider using evaluation metrics that are more sensitive to class imbalance, such as precision, recall, F1 score, or area under the ROC curve (AUC-ROC).
</p>
<p>
<strong>Model Architecture:</strong> Experiment with different architectures, hyperparameters, or even different models that may be more robust to class imbalance.
</p>

In [123]:
from transformers import BertTokenizer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk import pos_tag
from collections import defaultdict
from nltk.corpus import wordnet as wn
import tensorflow as tf

# Load the BERT tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Define NLTK resources
lemmatizer = WordNetLemmatizer()
english_stopwords = set(stopwords.words('english'))
NEGATION_SET = {"aren't", "won't", 'nor',  "doesn't", "weren't", "shan't", 'no', 'hadn', "couldn't", "don't", 'needn', "shouldn't",  'shouldn', 'mustn', "wasn't", 'isn', "needn't", 'ain', "hadn't", "haven't",  "didn't", 'didn', 'couldn', 'weren',  "mustn't", 'hasn', 'mightn', 'wouldn', "wouldn't",  "isn't", 'not', "hasn't",  'wasn',  'aren', 'haven', "mightn't",  'doesn',  'won', 'don'}
english_stopwords = english_stopwords - NEGATION_SET
tag_map = defaultdict(lambda : wn.NOUN)
tag_map['J'] = wn.ADJ
tag_map['V'] = wn.VERB
tag_map['R'] = wn.ADV

def preprocess_reviews_for_inference(reviews, max_length=64):
    # Convert to lowercase
    reviews = [review.lower() for review in reviews]

    # Tokenize using NLTK word tokenizer
    tokenized_reviews = [custom_tokenizer(review) for review in reviews]

    # Remove stopwords and perform lemmatization
    filtered_tokens = [[lemmatizer.lemmatize(word, tag_map[tag[0]]) for word, tag in pos_tag(review) 
                        if (word.isalpha() or word in NEGATION_SET) and word not in english_stopwords] 
                       for review in tokenized_reviews]

    # Pad tokenized reviews to match max_length
    padded_reviews = [review + ['[PAD]'] * (max_length - len(review)) if len(review) < max_length else review[:max_length] 
                      for review in filtered_tokens]

    # Tokenize using BERT tokenizer
    tokenized_inputs = tokenizer(
        [' '.join(review) for review in padded_reviews],
        add_special_tokens=True,
        padding=True, 
        truncation=True, 
        max_length=max_length, 
        return_tensors="tf"
    )

    return tokenized_inputs


In [124]:
prediction_input = preprocess_reviews_for_inference(["this app looks so ugly and sometimes its not even working!"])
print(prediction_input)

{'input_ids': <tf.Tensor: shape=(1, 64), dtype=int32, numpy=
array([[  101, 10439,  2298,  9200,  2823,  2025,  2130,  2147,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
          102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 64), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 64), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

F	BR	AU	FI	IR	A	L	LF	MN	O	PE	SC	SE	US	PO

In [37]:
model.predict({input1:prediction_input["input_ids"],input2:prediction_input["attention_mask"]})

NameError: name 'prediction_input' is not defined