In [1]:
import pandas as pd

# Load pickle data into a DataFrame
feature_obj = pd.read_pickle('../_3_data_preprocessing/output/serialized_review_dataframe.pkl')
df = pd.read_csv("../dataset/dataset1.csv",sep=",",header=0,quotechar='"')
# Display the DataFrame
print(feature_obj)  #Print the first few rows to verify


{'input_ids': <tf.Tensor: shape=(1234, 62), dtype=int32, numpy=
array([[  101,  2191,  2066, ...,     0,     0,     0],
       [  101,  3898,  2235, ...,     0,     0,     0],
       [  101,  6203, 20996, ...,     0,     0,     0],
       ...,
       [  101,  6904,  2615, ...,     0,     0,     0],
       [  101,  3291,  4030, ...,     0,     0,     0],
       [  101,  6592,  2048, ...,     0,     0,     0]])>, 'token_type_ids': <tf.Tensor: shape=(1234, 62), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])>, 'attention_mask': <tf.Tensor: shape=(1234, 62), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])>}


In [3]:
features = [{"input_ids":a,"attention_mask":b} for a,b in zip(feature_obj["input_ids"],feature_obj["attention_mask"])]
features

[{'input_ids': <tf.Tensor: shape=(62,), dtype=int32, numpy=
  array([  101,  2191,  2066,  2092,  5016, 10369,  2502,  2332, 10369,
           102,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0])>,
  'attention_mask': <tf.Tensor: shape=(62,), dtype=int32, numpy=
  array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])>},
 {'input_ids': <tf.Tensor: shape=(62,), dtype=int32, numpy=
  array([  101,  3898,  2235,  2438,  2302,  4306,  4933, 18029,  2717,
          5587,  2006,  20

In [4]:
from sklearn.model_selection import train_test_split

# Assume your DataFrame is named df
# Extract features (review_text) and labels (F, BR, AU, FI, IR, A, L, LF, MN, O, PE, SC, SE, US, PO)
labels = df[['F', 'BR', 'AU', 'FI', 'IR', 'A', 'L', 'LF', 'MN', 'O', 'PE', 'SC', 'SE', 'US', 'PO']]

# Split the dataset into training and validation sets
train_features, val_features, train_labels, val_labels = train_test_split(features, labels, test_size=0.2, random_state=42)

# Now you have your training and validation sets ready
# train_features and train_labels are for training
# val_features and val_labels are for validation


In [5]:
len(train_features)

987

In [6]:
train_labels

F  BR  AU  FI  IR  A  L  LF  MN  O  PE  SC  SE  US  PO
869   0   0   0   0   1  0  0   0   0  0   0   0   0   0   0
728   1   0   0   0   0  0  0   0   0  0   0   0   1   0   0
803   1   0   0   0   0  0  0   0   0  0   0   0   0   0   0
644   0   0   0   0   1  0  0   0   0  0   0   0   0   0   0
813   0   0   0   0   1  0  0   0   0  0   0   0   0   0   0
...  ..  ..  ..  ..  .. .. ..  ..  .. ..  ..  ..  ..  ..  ..
1044  0   0   0   0   0  0  0   0   0  0   0   0   0   1   0
1095  0   1   0   0   0  0  0   0   0  0   1   0   0   0   0
1130  0   0   0   0   1  0  0   0   0  0   0   0   0   0   0
860   0   0   0   0   1  0  0   0   0  0   0   0   0   0   0
1126  0   0   0   0   0  0  0   1   0  0   0   0   0   0   0

[987 rows x 15 columns]

ERROR

In [7]:
(feature_obj["attention_mask"].shape[1],)

(62,)

In [8]:
train_features

[{'input_ids': <tf.Tensor: shape=(62,), dtype=int32, numpy=
  array([  101,  2307, 10439,  4299,  2134,  1043, 15909,  2818,  6686,
           102,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0])>,
  'attention_mask': <tf.Tensor: shape=(62,), dtype=int32, numpy=
  array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])>},
 {'input_ids': <tf.Tensor: shape=(62,), dtype=int32, numpy=
  array([ 101, 2228, 2071, 2204, 2583, 2797, 4471, 2619, 2295, 2071, 3796,
         2711, 4471, 23

In [21]:
import tensorflow as tf
from transformers import TFBertModel
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model

from tensorflow.keras.preprocessing.sequence import pad_sequences


input_ids = Input(shape=(feature_obj["input_ids"].shape[1],), dtype=tf.int32)
attention_mask = Input(shape=(feature_obj["attention_mask"].shape[1],), dtype=tf.int32)

# Load BERT model
bert_model = TFBertModel.from_pretrained('bert-base-uncased')

bert_output = bert_model(input_ids, attention_mask=attention_mask)[1]
output = Dense(15, activation='sigmoid')(bert_output)

model = Model(inputs=[input_ids, attention_mask], outputs=output)

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(x={'input_1': feature_obj["input_ids"][:len(train_features)], 'input_2': feature_obj["input_ids"][:len(train_features)]},
          y=train_labels,
          epochs=5,
          batch_size=32,
          validation_split=0.2)

# Evaluate the model
results = model.evaluate(x={'input_1':feature_obj["input_ids"][len(train_features):],'input_2':feature_obj["input_ids"][len(train_features):]}, y=val_labels)
print("Validation Loss:", results[0])
print("Validation Accuracy:", results[1])

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

Epoch 1/5


ValueError: in user code:

    File "c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\engine\training.py", line 1377, in train_function  *
        return step_function(self, iterator)
    File "c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\engine\training.py", line 1360, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\engine\training.py", line 1349, in run_step  **
        outputs = model.train_step(data)
    File "c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\engine\training.py", line 1126, in train_step
        y_pred = self(x, training=True)
    File "c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\engine\input_spec.py", line 197, in assert_input_compatibility
        raise ValueError(

    ValueError: Missing data for input "input_5". You passed a data dictionary with keys ['input_1', 'input_2']. Expected the following keys: ['input_5', 'input_6']
